apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\scree\Downloads\kompose-windows-amd64.exe convert -c
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: service-db
  name: service-db
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5432
  selector:
    io.kompose.service: service-db
status:
  loadBalancer: {}
