# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rborodin/userservice-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80


## Application level settings
appMode: qa
databaseUser: qa-user
databasePassword: qa-password

appName: userservice
ingressedService: userservice-backend-service
apiHost: http://userservice-backend-service
appHost: userservice.local

apps:
  client-backend:
    appName: client-backend
    replicasCount: 1
    container:
      image: rborodin/userservice-app
      port: 8181
    service:
      port: 80
    targetPort: 8080